{
 "title": "Monitor Services",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"localhost:9090\",job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "In-Memory Chunks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks" }
   ]
  },
  {
   "title": "In-Memory Series",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  { "title": "Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"prometheus\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Head Time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "Time series" }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders",
     "legendFormat": "Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[1m])",
     "legendFormat": "Samples"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "Chunks" }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total[1m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total[1m])",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_min_time", "legendFormat": "Min" },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    { "expr": "prometheus_tsdb_head_max_time", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Head GC Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum[1m])",
     "legendFormat": "GC Time"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_blocks_loaded", "legendFormat": "Blocks Loaded" }
   ]
  },
  {
   "title": "TSDB Reloads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total[10m])",
     "legendFormat": "Reloads"
    }
   ]
  },
  {
   "title": "TSDB Problems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total[10m])",
     "legendFormat": "WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total[10m])",
     "legendFormat": "Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found[10m])",
     "legendFormat": "Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total[10m])",
     "legendFormat": "Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total[10m])",
     "legendFormat": "Retention Cutoff Failures"
    }
   ]
  },
  {
   "title": "WAL Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count[1m])",
     "legendFormat": "Fsync Latency"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count[1m])",
     "legendFormat": "Truncate Latency"
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total[10m])",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "Compaction Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum[10m])",
     "legendFormat": "Compaction Time"
    }
   ]
  },
  {
   "title": "Retention Cutoffs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_total[10m])",
     "legendFormat": "Retention Cutoffs"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count[10m])",
     "legendFormat": "Chunk Samples"
    }
   ]
  },
  {
   "title": "Target Scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m]) / rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Query engine timings",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum[1m])",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule group evaulation problems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total[1m])  ",
     "legendFormat": "Rule group missed"
    },
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total[1m])",
     "legendFormat": "Rule evals failed"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum[1m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  }
 ]
}